---
- name: Полная автоматизация Docker Compose через Ansible
  hosts: localhost
  become: true # Этот флаг заменяет слово "sudo" — Ansible будет выполнять задачи от имени администратора

  tasks:
    # Задача №1: Проверяем, установлена ли утилита curl (она нужна для системы)
    - name: Убедиться, что curl установлен в системе
      ansible.builtin.apt:
        name: curl
        state: present # present означает "должен быть установлен"

    # Задача №2: Проверяем, работает ли служба Docker
    - name: Убедиться, что служба Docker запущена и активна
      ansible.builtin.systemd:
        name: docker
        state: started
        enabled: true # Сделать так, чтобы Docker сам запускался при включении компьютера

    # Задача №3: Запускаем наш Docker Compose проект одной кнопкой
    - name: Запустить веб-сайт и базу данных через Docker Compose
      community.docker.docker_compose_v2:
        project_src: /home/qwer/app_project
        state: present
